### ISSUE TITLE
Planet "Pop xx max" display error

### ISSUE THREAD

**Issue by Gerwin2k** [1oom-fork/1oom#5]
Thanks for working on 1oom. 
See attached v1.7.5 save. 
It says for the "Crius" system, south-west on the star-map: Pop 50 Max / Pop(ulation) 125 / Planet size 125. 
That 50 is a display error AFAIK.
In this same game I have seen this Pop Max display error occur multiple times, in different places. This game was started in v1.7.5.

Edit: also seen it for a planet that was occupied by me.

[1oom_save5.zip](https://github.com/1oom-fork/1oom/files/10680748/1oom_save5.zip)

**Comment by 1oom-fork** [comment]
Thanks for testing the Silicoid race. This behavior reflects the pollution of the planet.
You can see the amount of pollution by double-clicking on a planet, or by clicking on the planet's image in the upper right corner. This behavior was present in the original version of the game, however it was not noticeable as the Silicoid race did not have pollution due to an error in pollution calculation. Unfortunately, this behavior is misleading.
You can disable pollution fix in Custom Game (rules -> waste calculation fix).
Thanks for the report. If you have suggestions about this issue, feel free to ask.

**Comment by Gerwin2k** [comment]
All good. Was just lack of game knowledge by me, and taking "pop xx max" a bit to literally. As the planet can actually hold more, just not in healthy way.

**Comment by 1oom-fork** [comment]
I think "+" should be drawn. The fact that it doesn't show up seems like a bug.
