### ISSUE TITLE
Good Proposition

### ISSUE THREAD

**Issue by ghost** [1oom-fork/1oom#78]
Welcome back, commander.
I have good idea about battle grid. Its possible to add movement range (optional of course) to battle grid?
All modern strategy games have this. Grid+movement range can make battle more pleasantly :) Simple graphic,
ex. brighten or darkened squares, only this.
And, I'm curious, in nearest future its any chanse add something graphic filter? Game include "best" and "linear", but its no good effect,
i tested many resolutions. I think majority players used standard "linear".  I know many old games which use many graphic filter,
 ex. HQ3x, or xBRZ.  is it a lot of work?   My question about filter its no super priority.
But only one thing always is lacking in MoO, grid + ship move range. I think is very important in turn battle strategy. 
 Can you imagine chess without chessboard? :D

**Comment by 1oom-fork** [comment]
Regarding the darkening. It's not so simple anymore. We have a limited palette of colors and we need to focus on the possibilities that have already been implemented in order to maintain style. When making the grid, I copied the grid of the main game map (Alt + m). So it would be nice to have alternative implementation options besides dimming. In any case, I will think what can be done.

**Comment by 1oom-fork** [comment]
Games of this genre, including chess, are characterized by highlighting the borders of cells in green or another color. This option seems realistic to me, but it will be necessary to carry out boundary calculations. Feel free to suggest options, maybe I don't see any simple solution.

**Comment by 1oom-fork** [comment]
I have ideas on how to implement shading on existing palettes that support fading, but there are a lot of nuances that need to be planned. I'm glad this idea came to my mind.
